services:
  db:
    image: mysql:8.2
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: katya1234
      MYSQL_DATABASE: task-planner
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pkatya1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: task-planner-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: 'r2dbc:mysql://root:katya1234@mysql-db:3306/task-planner'
      SPRING_R2DBC_USERNAME: 'root'
      SPRING_R2DBC_PASSWORD: 'katya1234'
      SPRING_FLYWAY_URL: 'jdbc:mysql://root:katya1234@mysql-db:3306/task-planner'
      SPRING_FLYWAY_USER: 'root'
      SPRING_FLYWAY_PASSWORD: 'root'
      JAVA_OPTS: '-Xmx512m'
    ports:
      - "8081:8081"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
    driver: local
  minio_data:
    driver: local
