server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://root:katya1234@localhost:3306/task-planner
    #url: r2dbc:pool:mysql://db:3307/task-planner
    username: root
    password: katya1234
  flyway:
    enabled: true
    url: jdbc:mysql://root:katya1234@localhost:3306/task-planner
    #url: jdbc:mysql://root:root@db:3307/task-planner
    locations: classpath:db/migration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: connect.smtp.bz
    port: 587
    username: admin@miniuser.ru
    password: HjeX4cIst5mw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  password:
    encoder:
      secret: F2K2DZ82odq$13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      key-length: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f86df20a499a7d3f91ff2a7c
  expiration: 7200
  issuer: PLANNER

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.kursovaya.controller

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: avatars
